name: CI

on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make style

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux (gcc 10)
            os: ubuntu-20.04
            CC: gcc-10
            CXX: g++-10
            env:
              SENTRY_BACKEND: breakpad
          - name: macOS (xcode)
            os: macOs-latest
            ERROR_ON_WARNINGS: 1
            env:
              SENTRY_BACKEND: crashpad
          - name: Windows (VS2017, 32bit)
            os: vs2017-win2016
            TEST_X86: 1
            env:
              SENTRY_BACKEND: breakpad
          - name: Windows (latest)
            os: windows-latest
            env:
              SENTRY_BACKEND: breakpad

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      ERROR_ON_WARNINGS: ${{ matrix.ERROR_ON_WARNINGS }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2

      - name: Installing Linux Dependencies
        if: ${{ runner.os == 'Linux' && !env['TEST_X86'] }}
        # workaround: https://github.com/actions/virtual-environments/issues/1536#issuecomment-698537248
        run: |
          sudo apt update
          sudo apt install clang-10 clang-tools g++-10 libcurl4-openssl-dev

      - name: Installing Linux 32-bit Dependencies
        if: ${{ runner.os == 'Linux' && env['TEST_X86'] }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install gcc-multilib g++-multilib zlib1g-dev:i386 libssl-dev:i386 libcurl4-openssl-dev:i386

      - name: Building
        shell: bash
        run: |
          cmake --version
          cmake -B build -DSENTRY_BUILD_SHARED_LIBS=OFF -DSENTRY_BACKEND=$SENTRY_BACKEND
          cmake --build build --parallel --config Release
          cmake --install build --prefix install --config Release

